import { Car, User, Advertisement, Conversation, Message, TechSpecs } from "@/types";

export const ADMIN_USER: User = {
  id: "admin",
  name: "Westcars Support",
  phone: "+233 30 200 0000",
  email: "admin@westcars.gh",
  location: "Accra, Ghana",
  avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  memberSince: "2020-01-01",
  isVerified: true,
  isAdmin: true,
  isDealer: false,
  verification: { phone: true, id: true, dealer: false },
  rating: 5.0,
  totalReviews: 0,
  totalListings: 0,
  trustScore: 100,
  totalSales: 0,
};

export const MOCK_USERS: User[] = [
  {
    id: "user1",
    name: "Kwame Asante",
    phone: "+233241234567",
    email: "kwame@example.com",
    location: "Accra",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    memberSince: "2022-01-15",
    isVerified: true,
    verification: { phone: true, id: true, dealer: false },
    rating: 4.8,
    totalReviews: 47,
    totalListings: 12,
    trustScore: 88,
    totalSales: 11,
  },
  {
    id: "user2",
    name: "Ama Mensah",
    phone: "+233209876543",
    email: "ama@example.com",
    location: "Kumasi",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    memberSince: "2021-06-10",
    isVerified: false,
    verification: { phone: true, id: false, dealer: false },
    rating: 4.2,
    totalReviews: 18,
    totalListings: 5,
    trustScore: 52,
    totalSales: 4,
  },
  {
    id: "user3",
    name: "Kofi Boateng",
    phone: "+233554567890",
    email: "kofi@example.com",
    location: "Takoradi",
    avatar: "https://randomuser.me/api/portraits/men/67.jpg",
    memberSince: "2023-03-22",
    isVerified: true,
    isDealer: true,
    verification: { phone: true, id: true, dealer: true },
    rating: 4.6,
    totalReviews: 31,
    totalListings: 8,
    trustScore: 94,
    totalSales: 7,
  },
];

export const MOCK_CARS: Car[] = [
  {
    id: "car1",
    brand: "Toyota",
    model: "Land Cruiser V8",
    year: 2020,
    price: 380000,
    mileage: 45000,
    fuelType: "Diesel",
    transmission: "Automatic",
    condition: "Foreign Used",
    location: "Accra",
    description:
      "Excellent condition Toyota Land Cruiser V8. Full leather interior, sunroof, all options. No accident history. Ready for registration.",
    images: [
      "https://images.unsplash.com/photo-1621993202908-12f2ca6c5a41?w=800",
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800",
    ],
    sellerId: "user1",
    seller: MOCK_USERS[0],
    isFeatured: true,
    isSponsored: false,
    views: 1243,
    rating: { overall: 4.7, comfort: 4.8, ergonomics: 4.6, performance: 4.9, safety: 4.7, reliability: 4.5, totalRatings: 23 },
    createdAt: "2024-01-10",
    category: "suv",
    techSpecs: {
      bodyType: "SUV 5-door",
      owners: 1,
      color: "Pearl White",
      trim: "VX Premium",
      country: "Japan",
      carClass: "J (Full-size SUV)",
      doors: 5,
      seats: 7,
      steering: "Left",
      length: 4950,
      width: 1980,
      height: 1890,
      wheelbase: 2850,
      clearance: 225,
      frontTrack: 1665,
      rearTrack: 1675,
      wheelSize: "285/60 R18",
      engineType: "Diesel, V8",
      engineLayout: "Front, longitudinal",
      engineDisplacement: "4.5L (4461 cc)",
      engineCode: "1VD-FTV",
      horsepower: 272,
      horsepowerRpm: "3,400 rpm",
      torque: "650 Nm",
      torqueRpm: "1,600–2,800 rpm",
      cylinderConfig: "V8, 32 valves, DOHC",
      fuelGrade: "Diesel",
      gearbox: "Automatic 6-speed",
      gears: 6,
      drive: "Full-time 4WD (A-TRAC)",
      curbWeight: 2550,
      maxWeight: 3100,
      tankVolume: 93,
      frontSuspension: "Independent, coil spring, stabilizer bar",
      rearSuspension: "Rigid axle, coil spring, stabilizer bar",
      frontBrakes: "Ventilated disc, 338×30 mm",
      rearBrakes: "Ventilated disc, 345×22 mm",
      maxSpeed: 180,
      acceleration: "9.6 s",
      fuelCity: "16.5 L/100km",
      fuelHighway: "10.5 L/100km",
      fuelMixed: "13.0 L/100km",
      co2: "341 g/km",
      euroStandard: "Euro 6",
      annualTax: 760,
    },
  },
  {
    id: "car2",
    brand: "Mercedes-Benz",
    model: "GLE 350",
    year: 2019,
    price: 450000,
    mileage: 62000,
    fuelType: "Diesel",
    transmission: "Automatic",
    condition: "Foreign Used",
    location: "Kumasi",
    description:
      "Clean Mercedes GLE350 with panoramic sunroof, leather seats, and full service history. No accidents. All papers intact.",
    images: [
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800",
      "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=800",
    ],
    sellerId: "user2",
    seller: MOCK_USERS[1],
    isFeatured: false,
    isSponsored: true,
    views: 876,
    rating: { overall: 4.5, comfort: 4.9, ergonomics: 4.7, performance: 4.4, safety: 4.6, reliability: 4.2, totalRatings: 15 },
    createdAt: "2024-01-08",
    category: "suv",
    techSpecs: {
      bodyType: "SUV 5-door",
      owners: 1,
      color: "Selenite Grey Metallic",
      trim: "AMG Line",
      country: "Germany",
      carClass: "E (Premium SUV)",
      doors: 5,
      seats: 5,
      steering: "Left",
      length: 4924,
      width: 2008,
      height: 1796,
      wheelbase: 2995,
      clearance: 190,
      frontTrack: 1684,
      rearTrack: 1686,
      wheelSize: "275/45 R21",
      engineType: "Diesel, Inline-6",
      engineLayout: "Front, longitudinal",
      engineDisplacement: "3.0L (2987 cc)",
      engineCode: "OM656",
      horsepower: 286,
      horsepowerRpm: "3,800 rpm",
      torque: "600 Nm",
      torqueRpm: "1,200–3,200 rpm",
      cylinderConfig: "Inline-6, 24 valves, DOHC",
      fuelGrade: "Diesel",
      gearbox: "Automatic 9G-Tronic",
      gears: 9,
      drive: "4MATIC (Permanent AWD)",
      curbWeight: 2120,
      maxWeight: 2720,
      tankVolume: 70,
      frontSuspension: "Independent, air spring, multi-link",
      rearSuspension: "Independent, air spring, multi-link",
      frontBrakes: "Ventilated disc, 360×36 mm",
      rearBrakes: "Ventilated disc, 360×24 mm",
      maxSpeed: 230,
      acceleration: "6.0 s",
      fuelCity: "10.2 L/100km",
      fuelHighway: "7.4 L/100km",
      fuelMixed: "8.5 L/100km",
      co2: "223 g/km",
      euroStandard: "Euro 6d",
      annualTax: 900,
    },
  },
  {
    id: "car3",
    brand: "Toyota",
    model: "Camry",
    year: 2018,
    price: 95000,
    mileage: 78000,
    fuelType: "Petrol",
    transmission: "Automatic",
    condition: "Ghana Used",
    location: "Accra",
    description:
      "Toyota Camry in great condition. Regular oil changes, new tires, cold AC. Owner traveling abroad. Price negotiable.",
    images: [
      "https://images.unsplash.com/photo-1616455579100-2ceaa4eb2d37?w=800",
      "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=800",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0729?w=800",
    ],
    sellerId: "user3",
    seller: MOCK_USERS[2],
    isFeatured: false,
    isSponsored: false,
    views: 534,
    rating: { overall: 4.2, comfort: 4.1, ergonomics: 4.3, performance: 4.0, safety: 4.3, reliability: 4.5, totalRatings: 8 },
    createdAt: "2024-01-05",
    category: "sedan",
    techSpecs: {
      bodyType: "Sedan 4-door",
      owners: 2,
      color: "Midnight Black",
      trim: "XSE V6",
      country: "Japan",
      carClass: "D (Mid-size Sedan)",
      doors: 4,
      seats: 5,
      steering: "Left",
      length: 4885,
      width: 1840,
      height: 1445,
      wheelbase: 2825,
      clearance: 145,
      frontTrack: 1570,
      rearTrack: 1580,
      wheelSize: "235/45 R18",
      engineType: "Petrol, Inline-4",
      engineLayout: "Front, transverse",
      engineDisplacement: "2.5L (2494 cc)",
      engineCode: "2AR-FE",
      horsepower: 181,
      horsepowerRpm: "6,000 rpm",
      torque: "231 Nm",
      torqueRpm: "4,100 rpm",
      cylinderConfig: "Inline-4, 16 valves, DOHC",
      fuelGrade: "Petrol 91",
      gearbox: "Automatic 8-speed",
      gears: 8,
      drive: "FWD",
      curbWeight: 1490,
      maxWeight: 1960,
      tankVolume: 60,
      frontSuspension: "Independent, MacPherson strut",
      rearSuspension: "Independent, double wishbone",
      frontBrakes: "Ventilated disc, 294×28 mm",
      rearBrakes: "Solid disc, 295×16 mm",
      maxSpeed: 180,
      acceleration: "9.2 s",
      fuelCity: "10.8 L/100km",
      fuelHighway: "7.4 L/100km",
      fuelMixed: "8.8 L/100km",
      co2: "204 g/km",
      euroStandard: "Euro 6",
      annualTax: 190,
    },
  },
  {
    id: "car4",
    brand: "Honda",
    model: "CR-V",
    year: 2021,
    price: 195000,
    mileage: 28000,
    fuelType: "Petrol",
    transmission: "Automatic",
    condition: "Foreign Used",
    location: "Tema",
    description:
      "Barely used Honda CR-V. Still under warranty. First owner. No scratches or dents.",
    images: [
      "https://images.unsplash.com/photo-1617814076229-5f2ce43d6c1a?w=800",
      "https://images.unsplash.com/photo-1551501889-f0d0a6fa1e67?w=800",
    ],
    sellerId: "user1",
    seller: MOCK_USERS[0],
    isFeatured: true,
    isSponsored: false,
    views: 2018,
    rating: { overall: 4.6, comfort: 4.5, ergonomics: 4.8, performance: 4.4, safety: 4.9, reliability: 4.7, totalRatings: 12 },
    createdAt: "2024-01-12",
    category: "suv",
    techSpecs: {
      bodyType: "Crossover SUV 5-door",
      owners: 1,
      color: "Lunar Silver Metallic",
      trim: "EX-L AWD",
      country: "Japan",
      carClass: "D (Compact Crossover)",
      doors: 5,
      seats: 5,
      steering: "Left",
      length: 4607,
      width: 1855,
      height: 1679,
      wheelbase: 2660,
      clearance: 208,
      frontTrack: 1605,
      rearTrack: 1610,
      wheelSize: "235/60 R18",
      engineType: "Petrol Turbo, Inline-4",
      engineLayout: "Front, transverse",
      engineDisplacement: "1.5L (1498 cc)",
      engineCode: "L15B7 VTEC Turbo",
      horsepower: 190,
      horsepowerRpm: "5,600 rpm",
      torque: "243 Nm",
      torqueRpm: "1,700–5,000 rpm",
      cylinderConfig: "Inline-4, 16 valves, DOHC",
      fuelGrade: "Petrol 91",
      gearbox: "CVT Automatic",
      gears: 7,
      drive: "Real-Time AWD",
      curbWeight: 1545,
      maxWeight: 2055,
      tankVolume: 57,
      frontSuspension: "Independent, MacPherson strut",
      rearSuspension: "Independent, multi-link",
      frontBrakes: "Ventilated disc, 315×25 mm",
      rearBrakes: "Solid disc, 282×10 mm",
      maxSpeed: 200,
      acceleration: "7.7 s",
      fuelCity: "9.8 L/100km",
      fuelHighway: "7.2 L/100km",
      fuelMixed: "8.3 L/100km",
      co2: "192 g/km",
      euroStandard: "Euro 6",
      annualTax: 390,
    },
  },
  {
    id: "car5",
    brand: "Hyundai",
    model: "Sonata",
    year: 2017,
    price: 72000,
    mileage: 105000,
    fuelType: "Petrol",
    transmission: "Automatic",
    condition: "Ghana Used",
    location: "Accra",
    description:
      "Hyundai Sonata with full service history. Great budget car for daily commute. AC working perfectly.",
    images: [
      "https://images.unsplash.com/photo-1601250504083-8e607a18edd1?w=800",
      "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800",
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800",
    ],
    sellerId: "user2",
    seller: MOCK_USERS[1],
    isFeatured: false,
    isSponsored: false,
    views: 312,
    rating: { overall: 3.8, comfort: 3.9, ergonomics: 3.7, performance: 3.6, safety: 3.9, reliability: 4.0, totalRatings: 5 },
    createdAt: "2024-01-02",
    category: "sedan",
    techSpecs: {
      bodyType: "Sedan 4-door",
      owners: 3,
      color: "Quartz White Pearl",
      trim: "2.4 GLS",
      country: "South Korea",
      carClass: "D (Mid-size Sedan)",
      doors: 4,
      seats: 5,
      steering: "Left",
      length: 4855,
      width: 1865,
      height: 1475,
      wheelbase: 2805,
      clearance: 142,
      frontTrack: 1607,
      rearTrack: 1614,
      wheelSize: "215/55 R17",
      engineType: "Petrol, Inline-4",
      engineLayout: "Front, transverse",
      engineDisplacement: "2.4L (2359 cc)",
      engineCode: "G4KJ MPI",
      horsepower: 185,
      horsepowerRpm: "6,000 rpm",
      torque: "241 Nm",
      torqueRpm: "4,000 rpm",
      cylinderConfig: "Inline-4, 16 valves, DOHC",
      fuelGrade: "Petrol 91",
      gearbox: "Automatic 6-speed",
      gears: 6,
      drive: "FWD",
      curbWeight: 1455,
      maxWeight: 1930,
      tankVolume: 70,
      frontSuspension: "Independent, MacPherson strut",
      rearSuspension: "Independent, multi-link",
      frontBrakes: "Ventilated disc, 305×26 mm",
      rearBrakes: "Solid disc, 280×11 mm",
      maxSpeed: 215,
      acceleration: "8.0 s",
      fuelCity: "11.4 L/100km",
      fuelHighway: "7.5 L/100km",
      fuelMixed: "9.1 L/100km",
      co2: "210 g/km",
      euroStandard: "Euro 6",
      annualTax: 144,
    },
  },
  {
    id: "car6",
    brand: "BMW",
    model: "X5 xDrive40i",
    year: 2020,
    price: 520000,
    mileage: 32000,
    fuelType: "Petrol",
    transmission: "Automatic",
    condition: "Foreign Used",
    location: "Accra",
    description:
      "Stunning BMW X5 xDrive40i. M Sport package, panoramic roof, 360-degree camera. One owner from Germany.",
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800",
      "https://images.unsplash.com/photo-1607853202273-232359f50c94?w=800",
    ],
    sellerId: "user3",
    seller: MOCK_USERS[2],
    isFeatured: true,
    isSponsored: true,
    views: 3401,
    rating: { overall: 4.9, comfort: 5.0, ergonomics: 4.8, performance: 4.9, safety: 4.8, reliability: 4.7, totalRatings: 31 },
    createdAt: "2024-01-14",
    category: "luxury",
    techSpecs: {
      bodyType: "SUV 5-door",
      owners: 1,
      color: "Carbon Black Metallic",
      trim: "M Sport Package",
      country: "Germany",
      carClass: "J (Luxury SUV)",
      doors: 5,
      seats: 5,
      steering: "Left",
      length: 4922,
      width: 2004,
      height: 1745,
      wheelbase: 2975,
      clearance: 205,
      frontTrack: 1704,
      rearTrack: 1717,
      wheelSize: "275/45 R20",
      engineType: "Petrol Turbo, Inline-6",
      engineLayout: "Front, longitudinal",
      engineDisplacement: "3.0L (2998 cc)",
      engineCode: "B58B30",
      horsepower: 340,
      horsepowerRpm: "5,500 rpm",
      torque: "450 Nm",
      torqueRpm: "1,500–5,200 rpm",
      cylinderConfig: "Inline-6, 24 valves, DOHC, TwinPower Turbo",
      fuelGrade: "Petrol 95",
      gearbox: "Automatic 8-speed Steptronic",
      gears: 8,
      drive: "xDrive (Permanent AWD)",
      curbWeight: 2030,
      maxWeight: 2780,
      tankVolume: 83,
      frontSuspension: "Independent, double-joint spring strut, air suspension",
      rearSuspension: "Independent, five-link, air suspension",
      frontBrakes: "Ventilated disc, 348×36 mm",
      rearBrakes: "Ventilated disc, 345×24 mm",
      maxSpeed: 250,
      acceleration: "5.5 s",
      fuelCity: "13.0 L/100km",
      fuelHighway: "8.9 L/100km",
      fuelMixed: "10.5 L/100km",
      co2: "239 g/km",
      euroStandard: "Euro 6d",
      annualTax: 1040,
    },
  },
  {
    id: "car7",
    brand: "Kia",
    model: "Sportage",
    year: 2019,
    price: 148000,
    mileage: 55000,
    fuelType: "Petrol",
    transmission: "Automatic",
    condition: "Foreign Used",
    location: "Kumasi",
    description:
      "Kia Sportage in excellent shape. Full spec with all options. Clean interior. No hidden faults.",
    images: [
      "https://images.unsplash.com/photo-1607853202273-232359f50c94?w=800",
      "https://images.unsplash.com/photo-1617814076229-5f2ce43d6c1a?w=800",
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800",
    ],
    sellerId: "user1",
    seller: MOCK_USERS[0],
    isFeatured: false,
    isSponsored: false,
    views: 689,
    rating: { overall: 4.3, comfort: 4.4, ergonomics: 4.2, performance: 4.1, safety: 4.5, reliability: 4.4, totalRatings: 9 },
    createdAt: "2024-01-07",
    category: "suv",
    techSpecs: {
      bodyType: "Crossover SUV 5-door",
      owners: 1,
      color: "Aurora Black Pearl",
      trim: "EX AWD",
      country: "South Korea",
      carClass: "D (Compact Crossover)",
      doors: 5,
      seats: 5,
      steering: "Left",
      length: 4480,
      width: 1855,
      height: 1645,
      wheelbase: 2670,
      clearance: 182,
      frontTrack: 1584,
      rearTrack: 1588,
      wheelSize: "235/55 R19",
      engineType: "Petrol, Inline-4",
      engineLayout: "Front, transverse",
      engineDisplacement: "2.4L (2359 cc)",
      engineCode: "G4KJ",
      horsepower: 181,
      horsepowerRpm: "6,000 rpm",
      torque: "232 Nm",
      torqueRpm: "4,000 rpm",
      cylinderConfig: "Inline-4, 16 valves, DOHC",
      fuelGrade: "Petrol 91",
      gearbox: "Automatic 6-speed",
      gears: 6,
      drive: "AWD (on-demand)",
      curbWeight: 1601,
      maxWeight: 2120,
      tankVolume: 55,
      frontSuspension: "Independent, MacPherson strut",
      rearSuspension: "Independent, multi-link",
      frontBrakes: "Ventilated disc, 300×26 mm",
      rearBrakes: "Solid disc, 284×10 mm",
      maxSpeed: 190,
      acceleration: "10.4 s",
      fuelCity: "12.0 L/100km",
      fuelHighway: "8.0 L/100km",
      fuelMixed: "9.6 L/100km",
      co2: "224 g/km",
      euroStandard: "Euro 6",
      annualTax: 296,
    },
  },
  {
    id: "car8",
    brand: "Toyota",
    model: "Hilux",
    year: 2022,
    price: 290000,
    mileage: 18000,
    fuelType: "Diesel",
    transmission: "Manual",
    condition: "Foreign Used",
    location: "Takoradi",
    description:
      "Brand new Toyota Hilux pickup. Perfect for off-road and heavy duty work. 4WD system. Side steps included.",
    images: [
      "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
      "https://images.unsplash.com/photo-1504215680853-026ed2a45def?w=800",
    ],
    sellerId: "user2",
    seller: MOCK_USERS[1],
    isFeatured: false,
    isSponsored: false,
    views: 921,
    rating: { overall: 4.7, comfort: 4.3, ergonomics: 4.4, performance: 4.9, safety: 4.6, reliability: 4.8, totalRatings: 16 },
    createdAt: "2024-01-09",
    category: "pickup",
    techSpecs: {
      bodyType: "Pickup 4-door (Double Cab)",
      owners: 1,
      color: "Glacier White",
      trim: "SR5 4×4",
      country: "Thailand",
      carClass: "T (Pickup Truck)",
      doors: 4,
      seats: 5,
      steering: "Left",
      length: 5340,
      width: 1855,
      height: 1815,
      wheelbase: 3085,
      clearance: 279,
      frontTrack: 1570,
      rearTrack: 1570,
      wheelSize: "265/60 R18",
      engineType: "Diesel, Inline-4",
      engineLayout: "Front, longitudinal",
      engineDisplacement: "2.8L (2754 cc)",
      engineCode: "2GD-FTV",
      horsepower: 204,
      horsepowerRpm: "3,400 rpm",
      torque: "500 Nm",
      torqueRpm: "1,600–2,800 rpm",
      cylinderConfig: "Inline-4, 16 valves, DOHC",
      fuelGrade: "Diesel",
      gearbox: "Manual 6-speed",
      gears: 6,
      drive: "4WD (part-time, Hi/Lo)",
      curbWeight: 1935,
      maxWeight: 3095,
      tankVolume: 80,
      frontSuspension: "Independent, double wishbone, coil spring",
      rearSuspension: "Leaf spring, semi-elliptic",
      frontBrakes: "Ventilated disc, 326×32 mm",
      rearBrakes: "Drum, 295×74 mm",
      maxSpeed: 175,
      acceleration: "10.5 s",
      fuelCity: "13.0 L/100km",
      fuelHighway: "9.0 L/100km",
      fuelMixed: "10.8 L/100km",
      co2: "283 g/km",
      euroStandard: "Euro 6",
      annualTax: 580,
    },
  },
  {
    id: "car9",
    brand: "Toyota",
    model: "Corolla Cross",
    year: 2024,
    price: 185000,
    mileage: 0,
    fuelType: "Hybrid",
    transmission: "Automatic",
    condition: "New",
    location: "Accra",
    description: "Brand new Toyota Corolla Cross Hybrid. Zero kilometres, factory warranty, fuel-efficient hybrid system. First owner. Available for immediate delivery.",
    images: [
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800",
      "https://images.unsplash.com/photo-1583267746897-2cf415887172?w=800",
      "https://images.unsplash.com/photo-1550355291-bbee04a92027?w=800",
    ],
    sellerId: "user3",
    seller: MOCK_USERS[2],
    isFeatured: true,
    isSponsored: false,
    views: 410,
    rating: { overall: 4.8, comfort: 4.7, ergonomics: 4.9, performance: 4.6, safety: 4.9, reliability: 4.8, totalRatings: 4 },
    createdAt: "2024-01-15",
    category: "suv",
    techSpecs: {
      bodyType: "Crossover SUV 5-door",
      owners: 0,
      color: "Precious White Pearl",
      trim: "GX Hybrid",
      country: "Japan",
      carClass: "C (Compact Crossover)",
      doors: 5,
      seats: 5,
      steering: "Left",
      length: 4460,
      width: 1825,
      height: 1620,
      wheelbase: 2640,
      clearance: 160,
      frontTrack: 1560,
      rearTrack: 1555,
      wheelSize: "225/60 R17",
      engineType: "Hybrid, Inline-4",
      engineLayout: "Front, transverse",
      engineDisplacement: "2.0L (1987 cc)",
      engineCode: "M20A-FXS",
      horsepower: 152,
      horsepowerRpm: "6,000 rpm",
      torque: "188 Nm",
      torqueRpm: "4,400 rpm",
      cylinderConfig: "Inline-4, 16 valves, DOHC + Electric Motor",
      fuelGrade: "Petrol 95",
      gearbox: "CVT e-CVT",
      gears: 0,
      drive: "AWD-i (Electric Rear Motor)",
      curbWeight: 1530,
      maxWeight: 2050,
      tankVolume: 43,
      frontSuspension: "Independent, MacPherson strut",
      rearSuspension: "Independent, double wishbone",
      frontBrakes: "Ventilated disc, 296×28 mm",
      rearBrakes: "Solid disc, 281×10 mm",
      maxSpeed: 175,
      acceleration: "8.1 s",
      fuelCity: "5.4 L/100km",
      fuelHighway: "5.1 L/100km",
      fuelMixed: "5.2 L/100km",
      co2: "121 g/km",
      euroStandard: "Euro 6d",
      annualTax: 370,
    },
  },
  {
    id: "car10",
    brand: "Lexus",
    model: "ES 300h",
    year: 2023,
    price: 420000,
    mileage: 0,
    fuelType: "Hybrid",
    transmission: "Automatic",
    condition: "New",
    location: "Accra",
    description: "Luxurious Lexus ES 300h hybrid. Zero km, full factory warranty. Executive sedan with Lexus premium interior, Mark Levinson sound, and self-charging hybrid.",
    images: [
      "https://images.unsplash.com/photo-1506015391300-4802dc74de2e?w=800",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0729?w=800",
    ],
    sellerId: "user1",
    seller: MOCK_USERS[0],
    isFeatured: true,
    isSponsored: true,
    views: 893,
    rating: { overall: 4.9, comfort: 5.0, ergonomics: 4.9, performance: 4.7, safety: 4.9, reliability: 4.9, totalRatings: 7 },
    createdAt: "2024-01-16",
    category: "sedan",
    techSpecs: {
      bodyType: "Sedan 4-door",
      owners: 0,
      color: "Sonic Titanium",
      trim: "F Sport",
      country: "Japan",
      carClass: "E (Executive Sedan)",
      doors: 4,
      seats: 5,
      steering: "Left",
      length: 4975,
      width: 1865,
      height: 1445,
      wheelbase: 2870,
      clearance: 145,
      frontTrack: 1590,
      rearTrack: 1605,
      wheelSize: "235/45 R18",
      engineType: "Hybrid, Inline-4",
      engineLayout: "Front, transverse",
      engineDisplacement: "2.5L (2494 cc)",
      engineCode: "A25A-FXS",
      horsepower: 218,
      horsepowerRpm: "5,700 rpm",
      torque: "221 Nm",
      torqueRpm: "3,600 rpm",
      cylinderConfig: "Inline-4, 16 valves, DOHC + Electric Motor",
      fuelGrade: "Petrol 95",
      gearbox: "CVT e-CVT",
      gears: 0,
      drive: "FWD",
      curbWeight: 1755,
      maxWeight: 2280,
      tankVolume: 50,
      frontSuspension: "Independent, MacPherson strut",
      rearSuspension: "Independent, multi-link",
      frontBrakes: "Ventilated disc, 324×28 mm",
      rearBrakes: "Solid disc, 310×16 mm",
      maxSpeed: 180,
      acceleration: "8.9 s",
      fuelCity: "5.9 L/100km",
      fuelHighway: "5.5 L/100km",
      fuelMixed: "5.7 L/100km",
      co2: "131 g/km",
      euroStandard: "Euro 6d",
      annualTax: 840,
    },
  },
  {
    id: "car11",
    brand: "Toyota",
    model: "HiAce GL",
    year: 2020,
    price: 165000,
    mileage: 38000,
    fuelType: "Diesel",
    transmission: "Manual",
    condition: "Foreign Used",
    location: "Kumasi",
    description: "Clean Toyota HiAce GL people carrier. 15-seater, great for church, school, or staff transport. Excellent AC, full service history.",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800",
      "https://images.unsplash.com/photo-1566933293069-b55c7f326dd4?w=800",
      "https://images.unsplash.com/photo-1543465077-db45d34b88a5?w=800",
    ],
    sellerId: "user2",
    seller: MOCK_USERS[1],
    isFeatured: false,
    isSponsored: false,
    views: 455,
    rating: { overall: 4.4, comfort: 4.2, ergonomics: 4.1, performance: 4.3, safety: 4.5, reliability: 4.6, totalRatings: 11 },
    createdAt: "2024-01-06",
    category: "van",
    techSpecs: {
      bodyType: "Minibus / Van 15-seater",
      owners: 1,
      color: "White",
      trim: "GL Commuter",
      country: "Japan",
      carClass: "N (Commercial Van)",
      doors: 4,
      seats: 15,
      steering: "Left",
      length: 5380,
      width: 1880,
      height: 2285,
      wheelbase: 3210,
      clearance: 185,
      frontTrack: 1645,
      rearTrack: 1635,
      wheelSize: "215/70 R16",
      engineType: "Diesel, Inline-4",
      engineLayout: "Front, longitudinal",
      engineDisplacement: "2.8L (2754 cc)",
      engineCode: "1GD-FTV",
      horsepower: 163,
      horsepowerRpm: "3,400 rpm",
      torque: "420 Nm",
      torqueRpm: "1,200–3,200 rpm",
      cylinderConfig: "Inline-4, 16 valves, DOHC",
      fuelGrade: "Diesel",
      gearbox: "Manual 6-speed",
      gears: 6,
      drive: "RWD",
      curbWeight: 2090,
      maxWeight: 3500,
      tankVolume: 70,
      frontSuspension: "Independent, coil spring",
      rearSuspension: "Leaf spring",
      frontBrakes: "Ventilated disc",
      rearBrakes: "Drum",
      maxSpeed: 160,
      acceleration: "14.0 s",
      fuelCity: "14.0 L/100km",
      fuelHighway: "9.5 L/100km",
      fuelMixed: "11.5 L/100km",
      co2: "298 g/km",
      euroStandard: "Euro 6",
      annualTax: 330,
    },
  },
  {
    id: "car12",
    brand: "Volkswagen",
    model: "Golf 8 GTI",
    year: 2021,
    price: 220000,
    mileage: 22000,
    fuelType: "Petrol",
    transmission: "Automatic",
    condition: "Foreign Used",
    location: "Accra",
    description: "Stunning VW Golf 8 GTI. Factory fresh interior, DSG gearbox, tech package. One careful owner from Germany. No accident history.",
    images: [
      "https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=800",
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800",
      "https://images.unsplash.com/photo-1617814076229-5f2ce43d6c1a?w=800",
    ],
    sellerId: "user3",
    seller: MOCK_USERS[2],
    isFeatured: false,
    isSponsored: false,
    views: 1102,
    rating: { overall: 4.7, comfort: 4.6, ergonomics: 4.8, performance: 4.9, safety: 4.7, reliability: 4.5, totalRatings: 14 },
    createdAt: "2024-01-11",
    category: "hatchback",
    techSpecs: {
      bodyType: "Hatchback 5-door",
      owners: 1,
      color: "Rabbit Blue Metallic",
      trim: "GTI DSG",
      country: "Germany",
      carClass: "C (Compact Hatchback)",
      doors: 5,
      seats: 5,
      steering: "Left",
      length: 4284,
      width: 1789,
      height: 1452,
      wheelbase: 2686,
      clearance: 143,
      frontTrack: 1546,
      rearTrack: 1534,
      wheelSize: "225/45 R18",
      engineType: "Petrol Turbo, Inline-4",
      engineLayout: "Front, transverse",
      engineDisplacement: "2.0L (1984 cc)",
      engineCode: "EA888 Gen4",
      horsepower: 245,
      horsepowerRpm: "5,000 rpm",
      torque: "370 Nm",
      torqueRpm: "1,600–4,500 rpm",
      cylinderConfig: "Inline-4, 16 valves, DOHC, TSI",
      fuelGrade: "Petrol 95",
      gearbox: "DSG 7-speed Dual Clutch",
      gears: 7,
      drive: "FWD",
      curbWeight: 1396,
      maxWeight: 1940,
      tankVolume: 50,
      frontSuspension: "Independent, MacPherson strut",
      rearSuspension: "Independent, multi-link",
      frontBrakes: "Ventilated disc, 340×30 mm",
      rearBrakes: "Solid disc, 310×22 mm",
      maxSpeed: 250,
      acceleration: "6.3 s",
      fuelCity: "9.5 L/100km",
      fuelHighway: "6.8 L/100km",
      fuelMixed: "7.8 L/100km",
      co2: "178 g/km",
      euroStandard: "Euro 6d",
      annualTax: 440,
    },
  },
  {
    id: "car13",
    brand: "Honda",
    model: "CB650R",
    year: 2022,
    price: 38000,
    mileage: 8500,
    fuelType: "Petrol",
    transmission: "Manual",
    condition: "Foreign Used",
    location: "Accra",
    description: "Clean Honda CB650R Neo Sports Cafe. Excellent condition. New tyres and service just done. Comes with full gear kit.",
    images: [
      "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800",
      "https://images.unsplash.com/photo-1558981359-219d6364c9c8?w=800",
      "https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=800",
    ],
    sellerId: "user1",
    seller: MOCK_USERS[0],
    isFeatured: false,
    isSponsored: false,
    views: 334,
    rating: { overall: 4.6, comfort: 4.2, ergonomics: 4.5, performance: 4.8, safety: 4.4, reliability: 4.7, totalRatings: 6 },
    createdAt: "2024-01-08",
    category: "motorcycle",
    techSpecs: {
      bodyType: "Naked Sport Motorcycle",
      owners: 1,
      color: "Graphite Black",
      trim: "Standard",
      country: "Japan",
      carClass: "M (Motorcycle)",
      doors: 0,
      seats: 2,
      steering: "Left",
      length: 2117,
      width: 780,
      height: 1062,
      wheelbase: 1450,
      clearance: 140,
      frontTrack: 0,
      rearTrack: 0,
      wheelSize: "120/70 ZR17 / 180/55 ZR17",
      engineType: "Petrol, Inline-4",
      engineLayout: "Transverse",
      engineDisplacement: "0.65L (648 cc)",
      engineCode: "PC64E",
      horsepower: 95,
      horsepowerRpm: "12,000 rpm",
      torque: "64 Nm",
      torqueRpm: "8,500 rpm",
      cylinderConfig: "Inline-4, 16 valves, DOHC",
      fuelGrade: "Petrol 95",
      gearbox: "Manual 6-speed",
      gears: 6,
      drive: "Chain drive",
      curbWeight: 202,
      maxWeight: 380,
      tankVolume: 15,
      frontSuspension: "Telescopic fork, 41 mm",
      rearSuspension: "Pro-Link, single shock",
      frontBrakes: "Twin disc, 310 mm, ABS",
      rearBrakes: "Single disc, 240 mm, ABS",
      maxSpeed: 210,
      acceleration: "3.2 s",
      fuelCity: "4.5 L/100km",
      fuelHighway: "3.8 L/100km",
      fuelMixed: "4.1 L/100km",
      co2: "95 g/km",
      euroStandard: "Euro 5",
      annualTax: 76,
    },
  },
  {
    id: "car14",
    brand: "Yamaha",
    model: "MT-07",
    year: 2021,
    price: 32000,
    mileage: 14000,
    fuelType: "Petrol",
    transmission: "Manual",
    condition: "Foreign Used",
    location: "Tema",
    description: "Yamaha MT-07 in great condition. Fun to ride, torquey parallel-twin engine. Maintained at authorised dealer. Perfect for daily commuting.",
    images: [
      "https://images.unsplash.com/photo-1594819047050-99defaec5e38?w=800",
      "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800",
      "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800",
    ],
    sellerId: "user2",
    seller: MOCK_USERS[1],
    isFeatured: false,
    isSponsored: false,
    views: 218,
    rating: { overall: 4.5, comfort: 4.1, ergonomics: 4.4, performance: 4.7, safety: 4.3, reliability: 4.6, totalRatings: 5 },
    createdAt: "2024-01-04",
    category: "motorcycle",
    techSpecs: {
      bodyType: "Naked Sport Motorcycle",
      owners: 1,
      color: "Midnight Black",
      trim: "Standard",
      country: "Japan",
      carClass: "M (Motorcycle)",
      doors: 0,
      seats: 2,
      steering: "Left",
      length: 2085,
      width: 745,
      height: 1080,
      wheelbase: 1400,
      clearance: 140,
      frontTrack: 0,
      rearTrack: 0,
      wheelSize: "120/70 ZR17 / 180/55 ZR17",
      engineType: "Petrol, Parallel-Twin",
      engineLayout: "Transverse",
      engineDisplacement: "0.69L (689 cc)",
      engineCode: "CP2",
      horsepower: 73,
      horsepowerRpm: "9,000 rpm",
      torque: "68 Nm",
      torqueRpm: "6,500 rpm",
      cylinderConfig: "Parallel-Twin, 8 valves, DOHC",
      fuelGrade: "Petrol 91",
      gearbox: "Manual 6-speed",
      gears: 6,
      drive: "Chain drive",
      curbWeight: 184,
      maxWeight: 355,
      tankVolume: 14,
      frontSuspension: "Telescopic fork, 41 mm",
      rearSuspension: "Link-type, single shock",
      frontBrakes: "Twin disc, 298 mm, ABS",
      rearBrakes: "Single disc, 245 mm, ABS",
      maxSpeed: 195,
      acceleration: "3.8 s",
      fuelCity: "4.8 L/100km",
      fuelHighway: "4.0 L/100km",
      fuelMixed: "4.3 L/100km",
      co2: "101 g/km",
      euroStandard: "Euro 5",
      annualTax: 64,
    },
  },
];

export const MOCK_ADS: Advertisement[] = [
  {
    id: "ad1",
    title: "Get Your Car Insured",
    subtitle: "Enterprise Insurance — Ghana's #1 Auto Insurer",
    image: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800",
    ctaText: "Get Quote",
    color: "#005F2B",
  },
  {
    id: "ad2",
    title: "Auto Loan — As Low As 18%",
    subtitle: "GCB Bank — Quick approval, easy repayment",
    image: "https://images.unsplash.com/photo-1559526323-cb2f2fe2591b?w=800",
    ctaText: "Apply Now",
    color: "#003D1A",
  },
  {
    id: "ad3",
    title: "Pre-Purchase Inspection",
    subtitle: "Know exactly what you're buying — certified mechanics",
    image: "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    ctaText: "Book Now",
    color: "#00873E",
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv1",
    participantId: "user1",
    participant: MOCK_USERS[0],
    carId: "car1",
    car: MOCK_CARS[0],
    lastMessage: "Is the price negotiable?",
    lastMessageTime: "2024-01-14T10:30:00Z",
    unreadCount: 2,
  },
  {
    id: "conv2",
    participantId: "user3",
    participant: MOCK_USERS[2],
    carId: "car4",
    car: MOCK_CARS[3],
    lastMessage: "Can I come see it this weekend?",
    lastMessageTime: "2024-01-13T16:45:00Z",
    unreadCount: 0,
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: "msg1",
    conversationId: "conv1",
    senderId: "currentUser",
    text: "Hello, I'm interested in your Toyota Land Cruiser.",
    timestamp: "2024-01-14T10:00:00Z",
  },
  {
    id: "msg2",
    conversationId: "conv1",
    senderId: "user1",
    text: "Hello! Yes, it's still available. Any questions?",
    timestamp: "2024-01-14T10:05:00Z",
  },
  {
    id: "msg3",
    conversationId: "conv1",
    senderId: "currentUser",
    text: "Is the price negotiable?",
    timestamp: "2024-01-14T10:30:00Z",
  },
];
