import { Car, User, Advertisement, Conversation, Message } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "user1",
    name: "Kwame Asante",
    phone: "+233 24 123 4567",
    email: "kwame@example.com",
    location: "Accra",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    memberSince: "2022-01-15",
    isVerified: true,
    rating: 4.8,
    totalReviews: 47,
    totalListings: 12,
  },
  {
    id: "user2",
    name: "Ama Mensah",
    phone: "+233 20 987 6543",
    email: "ama@example.com",
    location: "Kumasi",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    memberSince: "2021-06-10",
    isVerified: false,
    rating: 4.2,
    totalReviews: 18,
    totalListings: 5,
  },
  {
    id: "user3",
    name: "Kofi Boateng",
    phone: "+233 55 456 7890",
    email: "kofi@example.com",
    location: "Takoradi",
    avatar: "https://randomuser.me/api/portraits/men/67.jpg",
    memberSince: "2023-03-22",
    isVerified: true,
    rating: 4.6,
    totalReviews: 31,
    totalListings: 8,
  },
];

export const MOCK_CARS: Car[] = [
  {
    id: "car1",
    brand: "Toyota",
    model: "Land Cruiser V8",
    year: 2020,
    price: 380000,
    mileage: 45000,
    fuelType: "Petrol",
    transmission: "Automatic",
    condition: "Foreign Used",
    location: "Accra",
    description:
      "Excellent condition Toyota Land Cruiser V8. Full leather interior, sunroof, all options. No accident history. Ready for registration.",
    images: [
      "https://images.unsplash.com/photo-1621993202908-12f2ca6c5a41?w=800",
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800",
      "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800",
    ],
    sellerId: "user1",
    seller: MOCK_USERS[0],
    isFeatured: true,
    isSponsored: false,
    rating: {
      overall: 4.7,
      comfort: 4.8,
      ergonomics: 4.6,
      performance: 4.9,
      safety: 4.7,
      reliability: 4.5,
      totalRatings: 23,
    },
    createdAt: "2024-01-10",
    category: "suv",
  },
  {
    id: "car2",
    brand: "Mercedes-Benz",
    model: "GLE 350",
    year: 2019,
    price: 450000,
    mileage: 62000,
    fuelType: "Diesel",
    transmission: "Automatic",
    condition: "Foreign Used",
    location: "Kumasi",
    description:
      "Clean Mercedes GLE350 with panoramic sunroof, leather seats, and full service history. No accidents. All papers intact.",
    images: [
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800",
      "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=800",
    ],
    sellerId: "user2",
    seller: MOCK_USERS[1],
    isFeatured: false,
    isSponsored: true,
    rating: {
      overall: 4.5,
      comfort: 4.9,
      ergonomics: 4.7,
      performance: 4.4,
      safety: 4.6,
      reliability: 4.2,
      totalRatings: 15,
    },
    createdAt: "2024-01-08",
    category: "suv",
  },
  {
    id: "car3",
    brand: "Toyota",
    model: "Camry",
    year: 2018,
    price: 95000,
    mileage: 78000,
    fuelType: "Petrol",
    transmission: "Automatic",
    condition: "Ghana Used",
    location: "Accra",
    description:
      "Toyota Camry in great condition. Regular oil changes, new tires, cold AC. Owner traveling abroad. Price negotiable.",
    images: [
      "https://images.unsplash.com/photo-1616455579100-2ceaa4eb2d37?w=800",
    ],
    sellerId: "user3",
    seller: MOCK_USERS[2],
    isFeatured: false,
    isSponsored: false,
    rating: {
      overall: 4.2,
      comfort: 4.1,
      ergonomics: 4.3,
      performance: 4.0,
      safety: 4.3,
      reliability: 4.5,
      totalRatings: 8,
    },
    createdAt: "2024-01-05",
    category: "sedan",
  },
  {
    id: "car4",
    brand: "Honda",
    model: "CR-V",
    year: 2021,
    price: 195000,
    mileage: 28000,
    fuelType: "Petrol",
    transmission: "Automatic",
    condition: "Foreign Used",
    location: "Tema",
    description:
      "Barely used Honda CR-V. Still under warranty. First owner. No scratches or dents.",
    images: [
      "https://images.unsplash.com/photo-1617814076229-5f2ce43d6c1a?w=800",
      "https://images.unsplash.com/photo-1551501889-f0d0a6fa1e67?w=800",
    ],
    sellerId: "user1",
    seller: MOCK_USERS[0],
    isFeatured: true,
    isSponsored: false,
    rating: {
      overall: 4.6,
      comfort: 4.5,
      ergonomics: 4.8,
      performance: 4.4,
      safety: 4.9,
      reliability: 4.7,
      totalRatings: 12,
    },
    createdAt: "2024-01-12",
    category: "suv",
  },
  {
    id: "car5",
    brand: "Hyundai",
    model: "Sonata",
    year: 2017,
    price: 72000,
    mileage: 105000,
    fuelType: "Petrol",
    transmission: "Automatic",
    condition: "Ghana Used",
    location: "Accra",
    description:
      "Hyundai Sonata with full service history. Great budget car for daily commute. AC working perfectly.",
    images: [
      "https://images.unsplash.com/photo-1601250504083-8e607a18edd1?w=800",
    ],
    sellerId: "user2",
    seller: MOCK_USERS[1],
    isFeatured: false,
    isSponsored: false,
    rating: {
      overall: 3.8,
      comfort: 3.9,
      ergonomics: 3.7,
      performance: 3.6,
      safety: 3.9,
      reliability: 4.0,
      totalRatings: 5,
    },
    createdAt: "2024-01-02",
    category: "budget",
  },
  {
    id: "car6",
    brand: "BMW",
    model: "X5",
    year: 2020,
    price: 520000,
    mileage: 32000,
    fuelType: "Diesel",
    transmission: "Automatic",
    condition: "Foreign Used",
    location: "Accra",
    description:
      "Stunning BMW X5 xDrive40i. M Sport package, panoramic roof, 360-degree camera. One owner from Germany.",
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800",
      "https://images.unsplash.com/photo-1607853202273-232359f50c94?w=800",
    ],
    sellerId: "user3",
    seller: MOCK_USERS[2],
    isFeatured: true,
    isSponsored: true,
    rating: {
      overall: 4.9,
      comfort: 5.0,
      ergonomics: 4.8,
      performance: 4.9,
      safety: 4.8,
      reliability: 4.7,
      totalRatings: 31,
    },
    createdAt: "2024-01-14",
    category: "luxury",
  },
  {
    id: "car7",
    brand: "Kia",
    model: "Sportage",
    year: 2019,
    price: 148000,
    mileage: 55000,
    fuelType: "Petrol",
    transmission: "Automatic",
    condition: "Foreign Used",
    location: "Kumasi",
    description:
      "Kia Sportage in excellent shape. Full spec with all options. Clean interior. No hidden faults.",
    images: [
      "https://images.unsplash.com/photo-1607853202273-232359f50c94?w=800",
    ],
    sellerId: "user1",
    seller: MOCK_USERS[0],
    isFeatured: false,
    isSponsored: false,
    rating: {
      overall: 4.3,
      comfort: 4.4,
      ergonomics: 4.2,
      performance: 4.1,
      safety: 4.5,
      reliability: 4.4,
      totalRatings: 9,
    },
    createdAt: "2024-01-07",
    category: "suv",
  },
  {
    id: "car8",
    brand: "Toyota",
    model: "Hilux",
    year: 2022,
    price: 290000,
    mileage: 18000,
    fuelType: "Diesel",
    transmission: "Manual",
    condition: "Foreign Used",
    location: "Takoradi",
    description:
      "Brand new Toyota Hilux pickup. Perfect for off-road and heavy duty work. 4WD system. Side steps included.",
    images: [
      "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800",
    ],
    sellerId: "user2",
    seller: MOCK_USERS[1],
    isFeatured: false,
    isSponsored: false,
    rating: {
      overall: 4.7,
      comfort: 4.3,
      ergonomics: 4.4,
      performance: 4.9,
      safety: 4.6,
      reliability: 4.8,
      totalRatings: 16,
    },
    createdAt: "2024-01-09",
    category: "pickup",
  },
];

export const MOCK_ADS: Advertisement[] = [
  {
    id: "ad1",
    title: "Get Your Car Insured",
    subtitle: "Enterprise Insurance — Ghana's #1 Auto Insurer",
    image: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800",
    ctaText: "Get Quote",
    color: "#1A237E",
  },
  {
    id: "ad2",
    title: "Auto Loan — As Low As 18%",
    subtitle: "GCB Bank — Quick approval, easy repayment",
    image: "https://images.unsplash.com/photo-1559526323-cb2f2fe2591b?w=800",
    ctaText: "Apply Now",
    color: "#006400",
  },
  {
    id: "ad3",
    title: "Car Inspection Service",
    subtitle: "Know what you're buying — certified pre-purchase inspection",
    image: "https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800",
    ctaText: "Book Now",
    color: "#FF6B00",
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv1",
    participantId: "user1",
    participant: MOCK_USERS[0],
    carId: "car1",
    car: MOCK_CARS[0],
    lastMessage: "Is the price negotiable?",
    lastMessageTime: "2024-01-14T10:30:00Z",
    unreadCount: 2,
  },
  {
    id: "conv2",
    participantId: "user3",
    participant: MOCK_USERS[2],
    carId: "car4",
    car: MOCK_CARS[3],
    lastMessage: "Can I come see it this weekend?",
    lastMessageTime: "2024-01-13T16:45:00Z",
    unreadCount: 0,
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: "msg1",
    conversationId: "conv1",
    senderId: "currentUser",
    text: "Hello, I'm interested in your Toyota Land Cruiser.",
    timestamp: "2024-01-14T10:00:00Z",
  },
  {
    id: "msg2",
    conversationId: "conv1",
    senderId: "user1",
    text: "Hello! Yes, it's still available. Any questions?",
    timestamp: "2024-01-14T10:05:00Z",
  },
  {
    id: "msg3",
    conversationId: "conv1",
    senderId: "currentUser",
    text: "Is the price negotiable?",
    timestamp: "2024-01-14T10:30:00Z",
  },
];
